version: "3"
services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile
        image: "best-image-tests"
        volumes:
            - ./allure-results:/opt/app/allure-results
            - ./junit-results:/opt/app/junit-results
    selenium:
        image: selenium/standalone-firefox